@host = http://localhost:3000
@urlUsers = /api/users
@urlGroups = /api/groups
@urlBills = /api/bills



########### USERS ############

GET {{host}}{{urlUsers}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2ODI2NzM5NTAsImlhdCI6MTY4MjI0MTk1MH0.f_25ehp9LUCf6Q7CSUFmLXYEoI4gOzAHW3mWGpK-cm8

POST {{host}}{{urlUsers}}/register
Content-Type: application/json

{
    "username": "juanan",
    "email": "juanan@gmail.com",
    "password": "12345"
}

### POST LOGIN
POST {{host}}{{urlUsers}}/login
Content-Type: application/json

{
    "email": "gerard@gmail.com",
    "password": "Gerard1"
}

###

GET {{host}}{{urlGroups}}/4/search/sa
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2ODI0MTI3ODYsImlhdCI6MTY4MTk4MDc4Nn0.UwBCmhobbbVPUXaS6tCpU16-k1XJ0YSnJuVfsFuRdqo






########### GROUPS ###########

GET {{host}}{{urlGroups}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2ODE5MDM0MzksImlhdCI6MTY4MTQ3MTQzOX0.qeXAwFMjbtC-3FbJYHFlL-4lH7RXJtbI5BT68SKMVDk
###

GET {{host}}{{urlGroups}}/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2ODE5MDM0MzksImlhdCI6MTY4MTQ3MTQzOX0.qeXAwFMjbtC-3FbJYHFlL-4lH7RXJtbI5BT68SKMVDk

###
GET {{host}}{{urlGroups}}/id/39/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwIjoxNjgyNTg1MjAxLCJpYXQiOjE2ODIxNTMyMDF9.3rxPH2J1AQhofjwaMqF62YagpVKXTR2ms44QJImvj_o



###

POST {{host}}{{urlGroups}}/newGroup
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2ODI0MDg0NzAsImlhdCI6MTY4MTk3NjQ3MH0.WXOdBVJU4eLJ3PJp2tezAIZI2VxuF0h33j9SNWfLIoA
Content-Type: application/json

{
"name": "nuevoGrupo",
"date": "1992-06-07 11:00:00",
"description":"estos son gastos de sdfbsduf"


}

###
POST {{host}}{{urlGroups}}/4/adduser
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwIjoxNjgyNTg2NjI2LCJpYXQiOjE2ODIxNTQ2MjZ9.KEB0NgEPaKPAWPfmPLFa8Hz2nbsha68HQJSO2nVQWcI
Content-Type: application/json

{
    "username": "sara93"    
}


###
PUT {{host}}{{urlGroups}}/edit/24
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2ODIxNzMyOTQsImlhdCI6MTY4MTc0MTI5NH0.qjizAAcDQlxVvGu8Y5dwJT0SXhPM-yIrtXSCTGdwmrE
Content-Type: application/json

{
    "name": "jojojjojo",
    "date": "2023-02-12 12:00:00",
    "description":"estos son gastos del jojojojo"
}

###

DELETE {{host}}{{urlGroups}}/24
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2ODIxNzMyOTQsImlhdCI6MTY4MTc0MTI5NH0.qjizAAcDQlxVvGu8Y5dwJT0SXhPM-yIrtXSCTGdwmrE

###




########### BILLS ############


### COSAS PENDIENTES: 
GET {{host}}{{urlGroups}}/bills/20
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJleHAiOjE2ODI0OTY0MDAsImlhdCI6MTY4MjA2NDQwMH0.R0yKRK5TJs3s1IfTm5zPXQkpUkv41srJNFoX40prLNU

### GET one Bill
GET {{host}}{{urlGroups}}/bills/id/38
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2ODI1MDY2OTAsImlhdCI6MTY4MjA3NDY5MH0.fspza1fZVT_4RHIGl2Zy62Cm3Gu__tT7racAZPXsAFU

### GET BILL by name

GET {{host}}{{urlGroups}}/bills/search/9/bi
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwIjoxNjgyNzYzODM2LCJpYXQiOjE2ODIzMzE4MzZ9.pPVdwHoUqJBupzkcEGTnkC_O9Lw29GkSKgBOXtpOQWo


###

GET {{host}}{{urlGroups}}/bills/get/20
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJleHAiOjE2ODI1MTA0MTksImlhdCI6MTY4MjA3ODQxOX0.V5Sn3IcbVu4J8EpDmBHE8JvdS-gitFMVPgG8Usr8UwY

###
GET {{host}}{{urlGroups}}/bills/totalAmount/9
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwIjoxNjgyNTg2NjI2LCJpYXQiOjE2ODIxNTQ2MjZ9.KEB0NgEPaKPAWPfmPLFa8Hz2nbsha68HQJSO2nVQWcI







### GET debts groups
GET {{host}}{{urlGroups}}/bills/amount/debts/9/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwIjoxNjgyNzc0NzQ0LCJpYXQiOjE2ODIzNDI3NDR9.V4hbxLaotdrfG1gYKUboCCa8LSbmvwGsGNo4WnHoOik








### Create new bill
POST {{host}}{{urlGroups}}/bills/9/newBill
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwiZXhwIjoxNjgyNzc0NzQ0LCJpYXQiOjE2ODIzNDI3NDR9.V4hbxLaotdrfG1gYKUboCCa8LSbmvwGsGNo4WnHoOik
Content-Type: application/json


{
    "name": "prueba92",
    "date": "2021-11-01",
    "quantity": 100
   

}


### Make changes in a bill
PUT {{host}}{{urlGroups}}/bills/edit/42/105
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2ODI2NjgyMjcsImlhdCI6MTY4MjIzNjIyN30.x6z4U69yXv5iu-2VUGXhbAhyk4pj59TclYBA11gM5dg
Content-Type: application/json

{
    "name": "holii",
    "quantity": 200,
    "date":"2020-11-02"
    
}


### DELETE one bill
DELETE {{host}}{{urlGroups}}/bills/42/105
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2ODI2NjgyMjcsImlhdCI6MTY4MjIzNjIyN30.x6z4U69yXv5iu-2VUGXhbAhyk4pj59TclYBA11gM5dg