@host = http://localhost:3000
@urlUsers = /api/users
@urlGroups = /api/groups
@urlBills = /api/bills



########### USERS ############

POST {{host}}{{urlUsers}}/register
Content-Type: application/json

{
    "username": "juanan",
    "email": "juanan@gmail.com",
    "password": "12345"
}

### POST LOGIN
POST {{host}}{{urlUsers}}/login
Content-Type: application/json

{
    "email": "Lida@gmail.com",
    "password": "Lida1"
}

###

GET {{host}}{{urlGroups}}/4/search/sa
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2ODI0MTI3ODYsImlhdCI6MTY4MTk4MDc4Nn0.UwBCmhobbbVPUXaS6tCpU16-k1XJ0YSnJuVfsFuRdqo






########### GROUPS ###########

GET {{host}}{{urlGroups}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2ODE5MDM0MzksImlhdCI6MTY4MTQ3MTQzOX0.qeXAwFMjbtC-3FbJYHFlL-4lH7RXJtbI5BT68SKMVDk
###

GET {{host}}{{urlGroups}}/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2ODE5MDM0MzksImlhdCI6MTY4MTQ3MTQzOX0.qeXAwFMjbtC-3FbJYHFlL-4lH7RXJtbI5BT68SKMVDk
###

POST {{host}}{{urlGroups}}/newGroup
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2ODI0MDg0NzAsImlhdCI6MTY4MTk3NjQ3MH0.WXOdBVJU4eLJ3PJp2tezAIZI2VxuF0h33j9SNWfLIoA
Content-Type: application/json

{
"name": "nuevoGrupo",
"date": "2023-04-14 11:00:00",
"description":"estos son gastos de sdfbsduf"


}

###
POST {{host}}{{urlGroups}}/4/adduser
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJleHAiOjE2ODI0MzkxMjUsImlhdCI6MTY4MjAwNzEyNX0.chFOiO0C82WFWmtSiISdZlLOJDkHOjBR06oo2i-zvds
Content-Type: application/json

{
    "username": "juanan"    
}


###
PUT {{host}}{{urlGroups}}/edit/24
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2ODIxNzMyOTQsImlhdCI6MTY4MTc0MTI5NH0.qjizAAcDQlxVvGu8Y5dwJT0SXhPM-yIrtXSCTGdwmrE
Content-Type: application/json

{
    "name": "jojojjojo",
    "date": "2023-02-12 12:00:00",
    "description":"estos son gastos del jojojojo"
}

###

DELETE {{host}}{{urlGroups}}/24
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2ODIxNzMyOTQsImlhdCI6MTY4MTc0MTI5NH0.qjizAAcDQlxVvGu8Y5dwJT0SXhPM-yIrtXSCTGdwmrE







########### BILLS ############


### COSAS PENDIENTES: 
GET {{host}}{{urlGroups}}/bills/20
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJleHAiOjE2ODI0OTY0MDAsImlhdCI6MTY4MjA2NDQwMH0.R0yKRK5TJs3s1IfTm5zPXQkpUkv41srJNFoX40prLNU

### GET one Bill
GET {{host}}{{urlGroups}}/bills/38
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJleHAiOjE2ODI1MDQ3NjIsImlhdCI6MTY4MjA3Mjc2Mn0.cplQAex9eNi3mQwamn5J0Fu1jtJ2sVa6_9r8n9eK5Vw

### Create new bill
POST {{host}}{{urlGroups}}/bills/20/newBill
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJleHAiOjE2ODI0OTY0MDAsImlhdCI6MTY4MjA2NDQwMH0.R0yKRK5TJs3s1IfTm5zPXQkpUkv41srJNFoX40prLNU
Content-Type: application/json

{
    "name": "prueba33",
    "date": "2020-11-01",
    "quantity": 200
   

}


### Make changes in a bill
PUT {{host}}{{urlGroups}}/bills/edit/20/38
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJleHAiOjE2ODI0OTY0MDAsImlhdCI6MTY4MjA2NDQwMH0.R0yKRK5TJs3s1IfTm5zPXQkpUkv41srJNFoX40prLNU
Content-Type: application/json

{
    "name": "holii",
    "quantity": 200,
    "date":"2020-11-02"
    
}


### DELETE one bill
DELETE {{host}}{{urlBills}}/15
